version: "3"
services:
  app:
    container_name: fxrates-node-mongo
    restart: always
    build: .
    ports:
      - "443:3001"
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
